title: "Tian"
author: "tianzhanda"
description: "科技博客"
url: "https://tianzhanda.github.io"

minimal_mistakes_skin: "dark"

remote_theme: "mmistakes/minimal-mistakes@4.27.0"

markdown: kramdown
paginate: 5

enable_copy_code_button: true

breadcrumbs: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives

jekyll_archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

defaults:
  - scope:
      path: "_posts"
    values:
      layout: single
      author_profile: true
      toc: true
      read_time: true
      comments: true
      share: true
      related: true
